apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: usage
spec:
  version: "{{ .TagName }}"
  homepage: "https://github.com/mchmarny/kubectl-usage"
  shortDescription: "Rank pods/containers by CPU/memory usage (usage รท limit)"
  description: |
    kubectl plugin for analyzing Kubernetes resource usage by comparing actual metrics against resource limits, 
    designed with distributed systems best practices.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: "https://github.com/mchmarny/kubectl-usage/releases/download/{{ .TagName }}/kubectl-usage_{{ .TagName }}_darwin_amd64"
      sha256: "sha256:92e133a3bb94850166241b394c556be1392d515db184e5c43cded6a75c6ac4fe"
      bin: "kubectl-usage"
      files:
        - from: "kubectl-usage"
          to: "kubectl-usage"

    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: "https://github.com/mchmarny/kubectl-usage/releases/download/{{ .TagName }}/kubectl-usage_{{ .TagName }}_darwin_arm64"
      sha256: "sha256:2d731c4f839c37027ab2b919ebd65fbdf9c99c002cb2176fd1824ed9ef5fd14b"
      bin: "kubectl-usage"
      files:
        - from: "kubectl-usage"
          to: "kubectl-usage"

    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: "https://github.com/mchmarny/kubectl-usage/releases/download/{{ .TagName }}/kubectl-usage_{{ .TagName }}_linux_amd64"
      sha256: "sha256:7f1ccc177f16a4f438d55a8b2c1e799f69a8e4b8d19f4f1605beac900ac6918a"
      bin: "kubectl-usage"
      files:
        - from: "kubectl-usage"
          to: "kubectl-usage"

    - selector:
        matchLabels:
          os: linux
          arch: arm64
      uri: "https://github.com/mchmarny/kubectl-usage/releases/download/{{ .TagName }}/kubectl-usage_{{ .TagName }}_linux_arm64"
      sha256: "sha256:a5ff2df39e6506d9be70162bd4bb12cf2f92d86aa532f748745f43f6353a7cc8"
      bin: "kubectl-usage"
      files:
        - from: "kubectl-usage"
          to: "kubectl-usage"
